spring.application.name=Student_Reg

spring.datasource.url=jdbc:postgresql://dpg-da03tnm7bikc73ebqdhg-a:5432/studentdb_rl1u
spring.datasource.username=studentdb_rl1u_user
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:10000}
